# Generated by Django 5.2.15 on 2026-06-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User5Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn_raqami', models.CharField(max_length=20, unique=True)),
                ('muallif_ismi', models.CharField(max_length=200)),
                ('nashriyot_nomi', models.CharField(max_length=200)),
                ('nashr_yili', models.IntegerField()),
                ('sahifalar_soni', models.IntegerField()),
            ],
        ),
    ]
