# Generated by Django 5.2.15 on 2026-06-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilakkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('username', models.CharField(max_length=77)),
                ('age', models.IntegerField()),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('bala', 'Bala'), ('qiz', 'Qiz')], max_length=90)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
