# Generated by Django 5.2.15 on 2026-06-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User7Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tadbir_nomi', models.CharField(max_length=200)),
                ('tadbir_sanasi', models.DateTimeField()),
                ('joylashuv', models.CharField(max_length=200)),
                ('maksimal_ishtirokchilar', models.IntegerField()),
                ('chipta_narxi', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
