# Generated by Django 5.2.15 on 2026-06-22 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user7', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user7model',
            table='user7',
        ),
    ]
